# Generated by Django 3.0 on 2020-08-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0009_auto_20200829_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='a slug to identify posts by this category', max_length=250, verbose_name='slug'),
        ),
    ]
